JAVA_HOME = '/usr/lib/jvm/java-6-openjdk/'


{spawn, exec} = require 'child_process'

task 'watch', 'Build project from src/*.coffee to bin/*.js', ->
  exec 'mkdir -p bin/js/'
  coffee = spawn 'coffee', ['-cw', '-o', 'bin/js', 'src']
  coffee.stdout.on 'data', (data) -> console.log data.toString().trim()  

task 'clean', 'Clean /bin/*.js files', ->
  exec 'ls bin/js/*.js', (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr


